---

- hosts: all
  become: true
  tasks:
    - name: install updates (CentOS)
      tags: always
      when: ansible_distribution == "CentOS"
      dnf:
        update_only: yes
        update_cache: yes
    - name: install update (Ubuntu)
      tags: always
      when: ansible_distribution == "Ubuntu"
      apt:
        upgrade: dist
        update_cache: yes
      
- hosts: web_servers
  become: true
  tasks: 

    - name: install apache2 package for Ubuntu 
      tags: apache,apache2,ubuntu
      when: ansible_distribution == "Ubuntu"
      apt: 
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
    
    - name: install apache2 package for CentOS
      tags: apache,centos,httpd
      when: ansible_distribution == "CentOS"
      dnf: 
        name: 
          - httpd
          - php
        state: latest

- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package (CentOS)
      tags: centos,db,mariadb
      when: ansible_distribution == "CentOS"
      dnf:
        name: mariadb
        state: latest
    - name: install mariadb package (Ubuntu)
      tags: ubuntu,db,mariadb 
      when: ansible_distribution == "Ubuntu"
      apt:
        name: mariadb-server
        state: latest

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
